spring:
  config:
    import: "aws-parameterstore:/banking/rds/;/banking/frontend/"
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/bankingdb
    driver-class-name: org.postgresql.Driver
    username: bank_admin
    password: ${RDS_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}
    producer:
      properties:
        acks: all
        enable.idempotence: true
        retries: 5

  h2:
    console:
      enabled: false
      path:
      settings:
        web-allow-others:

logging:
  level:
    io.awspring.cloud.paramstore.AwsParamStorePropertySource: INFO
#    org.springframework.boot.context.config.ConfigDataEnvironment: TRACE
    com.portfolio.banking: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    org.springframework.jdbc.datasource: INFO
#    io.awspring.cloud.paramstore: DEBUG
    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: INFO

  file:
    name: /app/logs/banking-service.log

#my:
#  value: ${/banking/rds/password:NOT_SET}
#  value2: ${password:NOT_SET}

banking:
  account-service-url: http://${ACCOUNT_SERVICE_URL}
  cors:
    allowed-origins: ${FRONTEND_URL}