spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:

  h2:
    console:
      enabled: false
      path:
      settings:
        web-allow-others:

logging:
  level:
#    org.springframework.boot.context.config.ConfigDataEnvironment: TRACE
    com.portfolio.banking: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    org.springframework.jdbc.datasource: INFO
#    io.awspring.cloud.paramstore: DEBUG
    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: INFO

  file:
    name: /app/logs/banking-service.log

#my:
#  value: ${/banking/rds/password:NOT_SET}
#  value2: ${password:NOT_SET}

banking:
  account-service-url: http://account-service:8081
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost,http://localhost:5173}