spring:
  application:
    name: card-service
  main:
    web-application-type: none   # Critical for Lambda
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      dynamodb:
        endpoint: ${AWS_DYNAMODB_ENDPOINT:}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health