spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
  kafka:
    bootstrap-servers:

  h2:
    console:
      enabled: false
      path:
      settings:
        web-allow-others:

logging:
  level:
    org.springframework.boot.context: INFO
    com.portfolio.banking: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    org.springframework.jdbc.datasource: INFO
#    io.awspring.cloud.paramstore: DEBUG
    logging:
      level:
        org:
          hibernate:
            type:
              descriptor:
                sql: INFO

  file:
    name: /app/logs/account-service.log
